In [3]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.utils import shuffle

data = pd.read_csv("studentdata.csv")
data.head()

school sex  age address famsize Pstatus  Medu  Fedu     Mjob      Fjob  ...  \
0     GP   F   18       U     GT3       A     4     4  at_home   teacher  ...   
1     GP   F   17       U     GT3       T     1     1  at_home     other  ...   
2     GP   F   15       U     LE3       T     1     1  at_home     other  ...   
3     GP   F   15       U     GT3       T     4     2   health  services  ...   
4     GP   F   16       U     GT3       T     3     3    other     other  ...   

  famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3  
0      4        3      4     1     1      3        6   5   6   6  
1      5        3      3     1     1      3        4   5   5   6  
2      4        3      2     2     3      3       10   7   8  10  
3      3        2      2     1     1      5        2  15  14  15  
4      4        3      2     1     2      5        4   6  10  10  

[5 rows x 33 columns]

In [4]:
# first selected the necessary columns that we need to train a machine learning model for the task of student grades prediction. 
# G3 column is our target label and then I split the dataset into 20% testing and 80% training
data = data[["G1", "G2", "G3", "studytime", "failures", "absences"]]
predict = "G3"
x = np.array(data.drop([predict], 1))
y = np.array(data[predict])

from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size=0.2)

C:\Users\Tahir\AppData\Local\Temp/ipykernel_13724/2429479306.py:5: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  x = np.array(data.drop([predict], 1))


In [5]:
# import linear regression model and check accuracy
linear_regression = LinearRegression()
linear_regression.fit(xtrain, ytrain)
accuracy = linear_regression.score(xtest, ytest)
print(accuracy)

0.8340204174771945


In [6]:
# let’s have a look at the predictions made by the students’ grade prediction model
predictions = linear_regression.predict(xtest)
for i in range(len(predictions)):
    print(predictions[x], xtest[x], [ytest[x]])

[[12.96333675 11.57012751 12.79493766 10.61497743 11.57012751]
 [12.96333675 12.96333675 12.79493766 10.61497743 15.5663482 ]
 [ 4.55151645  6.42619406 12.79493766  6.9989267  10.70123046]
 ...
 [10.70123046  6.42619406 11.74671507  6.9989267   6.9989267 ]
 [14.97352889 13.87018511 11.74671507 10.61497743 10.61497743]
 [ 6.42619406 18.63021342 11.74671507 10.61497743 12.96333675]] [[[13 13  2  0  2]
  [12 12  3  0  2]
  [12 13  2  0  2]
  [11 11  2  0  0]
  [12 12  3  0  2]]

 [[13 13  2  0  2]
  [13 13  2  0  2]
  [12 13  2  0  2]
  [11 11  2  0  0]
  [15 15  2  0 10]]

 [[ 6  5  1  0  7]
  [ 8  7  2  0  4]
  [12 13  2  0  2]
  [ 9  8  2  1  0]
  [10 11  2  0  6]]

 ...

 [[10 11  2  0  6]
  [ 8  7  2  0  4]
  [12 12  2  0  0]
  [ 9  8  2  1  0]
  [ 9  8  2  1  0]]

 [[14 15  2  0  0]
  [11 12  2  0 54]
  [12 12  2  0  0]
  [11 11  2  0  0]
  [11 11  2  0  0]]

 [[ 8  7  2  0  4]
  [17 18  1  0  0]
  [12 12  2  0  0]
  [11 11  2  0  0]
  [13 13  2  0  2]]] [array([[13, 11, 12, 10, 11]